version: 2.1
orbs:
  node: circleci/node@4.2.0
workflows:
  node-tests:
    jobs:
      - node/test:
          name: Backend lint and style check
          run-command: lint-check
      - node/test:
          name: Frontend lint and style check
          app-dir: client
          run-command: lint-check
